# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

theme: minimal
day_night: true
font: 'fira-sans'
font_size: M

# SEO

site_type: Person
local_business_type: ''
org_name: 'McGill University'
description: 'Personal website for Sam Harper'
twitter: 'sbh4th'

# Contact (edit or remove options as required)

email: sam.harper@mcgill.ca
phone: +1 514 398 2856
address:
  street: 1020 Pine Avenue West
  city: Montreal
  region: QC
  postcode: '94305'
  country: Canada
  country_code: CAN
coordinates:
  latitude: '45.504755'
  longitude: '-73.581860'
directions:
office_hours:
  - 'By appointment'
appointment_url:
contact_links:
  - icon: twitter
    icon_pack: fab
    name: DM Me
    link: 'https://twitter.com/Twitter'
  - icon: skype
    icon_pack: fab
    name: Skype Me
    link: 'skype:sbh4th?call'
  # - icon: keybase
  #   icon_pack: fab
  #   name: Chat on Keybase
  #   link: 'https://keybase.io/'
  # - icon: comments
  #   icon_pack: fas
  #   name: Discuss on Forum
  #   link: 'https://discourse.gohugo.io'

# Site header

main_menu:
  enable: true
  align: r
  show_logo: true
  show_language: false
  show_day_night: true
  show_search: true
  highlight_active_link: true

# Localization

date_format: '2006-01-02'
time_format: '15:04'
address_format: en-us

# Site features

highlight: true
highlight_languages:
  - r
math: true
diagram: true
privacy_pack: false
edit_page:
  repo_url: ''
  content_dir: ''
  repo_branch: main
  editable:
    page: false
    post: false
    book: false
show_related:
  book: true
  page: false
  post: true
  project: true
  publication: true
  event: true
reading_time: true
section_pager: false
docs_section_pager: true
sharing: true
copyright_license:
  enable: false
  allow_derivatives: false
  share_alike: true
  allow_commercial: false
  notice: 'This work is licensed under {license}'
abstract_length: 135
plugins_js: []
avatar:
  gravatar: true
  shape: circle
publications:
  date_format: January 2006
  citation_style: apa
projects:
  post_view: 2
  publication_view: 2
  talk_view: 2
breadcrumb:
  page_types:
    book: true
comments:
  provider: ''
  commentable:
    post: true
    book: true
    project: true
    publication: true
    event: true
  disqus:
    shortname: 'sbh4th-github-io'
    show_count: true
  commento:
    url: ''
search:
  provider: wowchemy
  algolia:
    app_id: ''
    api_key: ''
    index_name: ''
    show_logo: false
map:
  provider: 'Google Maps'
  api_key: 'AIzaSyBh6uB2jN2m7CKsZjnUfOrFS0HzhbPoRKU'
  zoom: 15
marketing:
  google_analytics: 'UA-124630930-1'
  google_tag_manager: ''
  google_site_verification: ''
  baidu_site_verification: ''
  baidu_tongji: ''
cms:
  branch: master
  local_backend: false
icon:
  pack:
    ai: true
